// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMdX67EPqk-Ni_8ifEzoksdFrAiLn9oGA',
    appId: '1:12310739126:web:aa177fb2014245aec64e17',
    messagingSenderId: '12310739126',
    projectId: 'chatapp-ceb33',
    authDomain: 'chatapp-ceb33.firebaseapp.com',
    storageBucket: 'chatapp-ceb33.firebasestorage.app',
    measurementId: 'G-L0YJ54KKSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2_wSgGpQQiqtDCdwtR37SxkNW4RKGVI',
    appId: '1:12310739126:android:596445b8c64b967ac64e17',
    messagingSenderId: '12310739126',
    projectId: 'chatapp-ceb33',
    storageBucket: 'chatapp-ceb33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnSDJoa0TtuZhRE8CG6-gXb9AHK_-vDWI',
    appId: '1:12310739126:ios:d5a69455461c0059c64e17',
    messagingSenderId: '12310739126',
    projectId: 'chatapp-ceb33',
    storageBucket: 'chatapp-ceb33.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnSDJoa0TtuZhRE8CG6-gXb9AHK_-vDWI',
    appId: '1:12310739126:ios:d5a69455461c0059c64e17',
    messagingSenderId: '12310739126',
    projectId: 'chatapp-ceb33',
    storageBucket: 'chatapp-ceb33.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMdX67EPqk-Ni_8ifEzoksdFrAiLn9oGA',
    appId: '1:12310739126:web:2b1c51223a2dad88c64e17',
    messagingSenderId: '12310739126',
    projectId: 'chatapp-ceb33',
    authDomain: 'chatapp-ceb33.firebaseapp.com',
    storageBucket: 'chatapp-ceb33.firebasestorage.app',
    measurementId: 'G-3R7SECV3HY',
  );
}
